global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'salon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['salonservice:8080']
        labels:
          application: 'Product Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'